
[build-system]
requires = ["pybind11==2.10.*", "scikit-build-core"]
build-backend = "scikit_build_core.build"

[project]
name = "dtcc-io"
version = "0.2.1"
description = "IO code for DTCC platform"
authors = [
  { name = "Dag Wästberg", email = "dwastberg@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: C++",
  "License :: OSI Approved :: MIT License"
]
dependencies = [
  "laspy[lazrs] >= 2.4.1",
  "numpy >= 1.24.2",
  "protobuf >= 3.20.0, < 3.21.0",
  "pybind11 >= 2.10.0, < 2.11.0",
  "Fiona >= 1.9.1",
  "rasterio >= 1.3.6",
  "shapely >= 2.0.1",
  "meshio >= 5.3.4",
  "pyassimp >= 4.1.4"
]

[project.optional-dependencies]
test = ["pytest"]


[tool.scikit-build]
wheel.expand-macos-universal-tags = true

[tool.cibuildwheel]
test-command = "pytest {project}/tests"
build-verbosity = 1
