
[build-system]
requires = ["scikit-build-core", "pybind11==2.10.*"]
build-backend = "scikit_build_core.build"

[project]
name = "dtcc-io"
version = "0.2.2"
description = "DTCC IO"
readme = "README.md"
authors = [
  { name = "Dag Wästberg", email = "dwastberg@gmail.com" },
  { name = "Anders Logg", email = "logg@chalmers.se" }
]
requires-python = ">=3.8"
classifiers = [
  "Intended Audience :: Science/Research",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: C++",
  "License :: OSI Approved :: MIT License"
]
dependencies = [
  "pybind11 >= 2.10.0, < 2.11.0",
  "protobuf >= 3.20.0, < 3.21.0",
  "laspy[lazrs]",
  "numpy >= 1.20.0, < 2.0.0",
  "Fiona",
  "rasterio",
  "shapely",
  "meshio",
  "pyassimp",
  "dtcc-model@git+https://github.com/dtcc-platform/dtcc-model.git@dev/new-build-system"
]

[project.optional-dependencies]
test = ["pytest"]

[tool.scikit-build]
wheel.expand-macos-universal-tags = true

[tool.cibuildwheel]
test-command = "pytest {project}/tests"
build-verbosity = 1
